### PR TITLE
use `which` to resolve codemod path

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #184

@bendemboski Do you think this will work? It avoids the complexity in this app.

### CODE REVIEW

**Comment by bendemboski** [comment]
Doesn't work for me ☹️ 

```
~/projects/groening$ ember-cli-update 
/Users/ben/.config/yarn/global/node_modules/which/which.js:134
  throw getNotFoundError(cmd)
  ^

Error: not found: ember-modules-codemod
    at getNotFoundError (/Users/ben/.config/yarn/global/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/Users/ben/.config/yarn/global/node_modules/which/which.js:134:9)
    at Object.<anonymous> (/Users/ben/.config/yarn/global/node_modules/ember-cli-update/src/index.js:15:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
~/projects/groening$ 
```

Maybe because `ember-modules-codemod` isn't set up to publish its binary to `.bin`?

**Comment by rwjblue** [comment]
@kellyselden - I didn’t fully follow the discussion in the issue, but any reason to avoid using `execa` here? It supports invoking binaries from installed npm packages out of the box (and returns a promise)...

**Comment by bendemboski** [comment]
@rwjblue the issue here has to do with to what level `ember-modules-codemod` is hoisted. You can end up with this directory structure wherever you have `ember-cli-update` installed:

```
node_modules
 └── ember-cli-update
     └── node_modules
         └── ember-modules-codemod
```

or this one:

```
node_modules
 ├── ember-cli-update
 └── ember-modules-codemod
```

Since `ember-modules-codemod` doesn't have a `main`, we can't just `require.resolve` it to find the path to it, and when it gets installed as a dependency of `ember-cli-update` (at least on my system, using the latest `yarn global add`), its binary doesn't end up getting symlinked into my path.

That's what we're grappling with here. The most robust solution I can think of would be to give `ember-modules-codemod` a `main` that allows API invocation, but I don't know how straightforward that would be.

Regardless, I'm personally a big fan of `execa` :)

**Comment by rwjblue** [comment]
I was referring to using `execa`'s `preferlocal` option (documented [here](https://github.com/sindresorhus/execa#preferlocal)) which should resolve the binary automatically just like a `npm` script would.  I still _think_ that should work fine?

**Pull request closed without merging**
