### PR TITLE
smart merge package.json

### LINKED ISSUE #68: More intelligent handling of `package.json`.
After running ember-cli-update on ~ 25 or so  addons (and learning how to use `git mergetool`) I've found that fixing up the merge conflicts in `package.json` end up being the most time consuming.  I think we can do even better than `git` for this specific file.

In general, I'd like to:

1. Run [sort-package-json](https://github.com/keithamus/sort-package-json) (to ensure the correct sort order before applying).
2. Leverage [three-way-merger](https://github.com/bantic/three-way-merger) to update the specific `dependencies` / `devDependencies` required. 
3. Generate a patch of the `package.json` files (using `--from` and `--to` versions) excluding changes in `dependencies` and `devDependencies` using [RFC6902](https://www.npmjs.com/package/rfc6902) and apply them.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #68.

- [x] resolve https://github.com/chbrown/rfc6902/issues/22
- [x] resolve https://github.com/joliss/node-fixturify/issues/8
- [x] add workaround for https://github.com/kellyselden/ember-cli-update/pull/108#issuecomment-327652340 if the above isn't fixed
- [x] merge https://github.com/kellyselden/git-diff-apply/pull/68
- [x] merge https://github.com/bantic/three-way-merger/pull/12
- [x] merge https://github.com/bantic/three-way-merger/pull/15
- [ ] merge https://github.com/npm/node-semver/pull/208
- [x] resolve https://github.com/jprichardson/node-jsonfile/issues/87
- [x] merge https://github.com/tomdale/ember-cli-addon-tests/pull/153
- [x] decide if we want this default or opt in behavior (via `--auto-merge-package-json`)
- [x] update README
- [x] fix merging from https://github.com/kellyselden/ember-cli-update/pull/108#issuecomment-327575806
- [x] stage package.json after merge

cc @rwjblue @seawatts @san650 @kategengler

### CODE REVIEW

**Comment by kellyselden** [comment]
I don't think merge is correct, this just happened:

screen shot 2017-09-06 at 11 41 06 am

**Comment by kellyselden** [comment]
package.json needs to be staged after merge.

**Comment by kellyselden** [comment]
If symlinks are broken in node_modules (npm link ember-cli, then delete globally), you get this error

```
  ember-cli-update Error: ENOENT: no such file or directory, stat './node_modules/.bin/ember'
  ember-cli-update     at Object.fs.statSync (fs.js:968:11)
  ember-cli-update     at Object.statSync (/Users/kelly.selden/code/ember-cli-update/node_modules/graceful-fs/polyfills.js:297:22)
  ember-cli-update     at readSync (/Users/kelly.selden/code/ember-cli-update/node_modules/fixturify/index.js:10:20)
  ember-cli-update     at readSync (/Users/kelly.selden/code/ember-cli-update/node_modules/fixturify/index.js:14:20)
  ember-cli-update     at Object.readSync (/Users/kelly.selden/code/ember-cli-update/node_modules/fixturify/index.js:14:20)
  ember-cli-update     at convertToObj (/Users/kelly.selden/code/ember-cli-update/node_modules/git-diff-apply/src/index.js:98:23)
  ember-cli-update     at ncp.then (/Users/kelly.selden/code/ember-cli-update/node_modules/git-diff-apply/src/index.js:56:16) +0ms
```

fixturify is trying to crawl it and failing. All the more reason to get https://github.com/joliss/node-fixturify/issues/8 done.

**Comment by kellyselden** [comment]
This has been working so well for me that I don't think an opt-in option would be worth it, so it will just be default.

**Comment by kellyselden** [comment]
Woohoo!

**Comment by kellyselden** [comment]
Released in v0.7.0

**Comment by rwjblue** [comment]
👏🙌😻

**Pull request merged**
